### ISSUE TITLE
Failure during installation : missing dependency ?

### ISSUE THREAD

**Issue by flotho** [OCA/odoo-test-helper#12]
Hi,

I have the following error during installation :
```    
pip2.7 install odoo-test-helper --user  
Collecting odoo-test-helper
  Using cached https://files.pythonhosted.org/packages/df/df/27b68a562a3112cf2a3da456a0848f2c5e37bdf8329d319d328c67154f7f/odoo-test-helper-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/easy_install-aS4RqI/setuptools_scm-6.0.1/src
    <pkg_resources.WorkingSet object at 0x7f6e30f7f390>
    Traceback (most recent call last):
      File "<string>", line 1, in <module>

.../...
File "/tmp/easy_install-aS4RqI/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 8, in <module>
    
      File "/tmp/easy_install-aS4RqI/setuptools_scm-6.0.1/src/setuptools_scm/config.py", line 6, in <module>
      File "/tmp/easy_install-aS4RqI/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
        print(*k)
              ^
    SyntaxError: invalid syntax
```

I solved this by upgrading setuptools and the installing wheel is marked as dependency.

what is your recommandation? add a dependency in this module?

Regards

**Comment by flotho** [comment]
I added dependencies in my deployment scripts.
But I suggest anyway to add wheel requirement in this module.

Regards
