### ISSUE TITLE
[15.0] FakeModelLoader inheriting res.users on HttpCase

### ISSUE THREAD

**Issue by CarlosRoca13** [OCA/odoo-test-helper#26]
## Module
[web_pivot_computed_measure](https://github.com/OCA/web/tree/15.0/web_pivot_computed_measure)

## Describe the bug
When we test the web_pivot_computed_measure module with some other module that is touching some res.users record (e.g. privacy_consent), we are getting exceptions that one of the added fields does not exist. 

I've tried adding the TearDownClass method to restore the registry but I still get the same error.
```python
@classmethod
def tearDownClass(cls):
    cls.loader.restore_registry()
    super().tearDownClass()
```

I also tried to add in the setUpClass the line cls.addClassCleanup(cls.loader.restore_registry) but I still get the same result.
```python
    ...
    cls.loader.backup_registry()
    cls.addClassCleanup(cls.loader.restore_registry)
    from .res_users_fake import ResUsersFake
    ...
```

I have seen that the use with HttpCase is with SetUp and with TearDown, I have made the change trying also to add the line self.addCleanup(self.loader.restore_registry) but I still have the same error.

I don't know if it's a FakeModelLoader error or if I'm doing something incorrectly.

Thanks in advance

ping @chienandalu

**Comment by CarlosRoca13** [comment]
Here are links to the tests and to the FakeModel statement.

- https://github.com/OCA/web/blob/98c78299a57dc60d40d6d7a83e0477c16de7e618/web_pivot_computed_measure/tests/test_ui_pivot.py#L1-L37
- https://github.com/OCA/web/blob/98c78299a57dc60d40d6d7a83e0477c16de7e618/web_pivot_computed_measure/tests/res_users_fake.py#L1-L12

Also, here is an example of the error I'm getting in the tests:
```
2023-04-05 10:18:04,047 1 ERROR devel odoo.addons.privacy_consent.tests.test_consent: ERROR: ActivityCase.test_template_required_auto
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
KeyError: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1082, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'res.users(1,).company_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/auto/addons/privacy_consent/tests/test_consent.py", line 30, in setUp
    self.partners += self.partners.create(
  File "<decorator-gen-102>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 621, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-133>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/auto/addons/mail/models/mail_thread.py", line 265, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-71>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 4018, in create
    vals = self._add_missing_default_values(vals)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1956, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_partner.py", line 145, in default_get
    values = super().default_get(default_fields)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 1392, in default_get
    ir_defaults = self.env['ir.default'].get_model_defaults(self._name)
  File "<decorator-gen-60>", line 2, in get_model_defaults
  File "/opt/odoo/custom/src/odoo/odoo/tools/cache.py", line 83, in lookup
    key = key0 + self.key(*args, **kwargs)
  File "<string>", line 1, in <lambda>
  File "/opt/odoo/custom/src/odoo/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 640, in company
    return self.user.company_id.with_env(self)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 2617, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/custom/src/odoo/odoo/fields.py", line 1108, in __get__
    recs._fetch_field(self)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3278, in _fetch_field
    self._read(fnames)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/res_users.py", line 452, in _read
    super(Users, self)._read(fields)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 3345, in _read
    cr.execute(query_str, params + [sub_ids])
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedColumn: column res_users.user_year_born does not exist
LINE 1: ..."res_users"."odoobot_failed" as "odoobot_failed", "res_users...
                                                             ^

**Comment by simahawk** [comment]
@CarlosRoca13 I'm about to tag a new release w/ 2 fixes that might help with your issue: #28 + #27.
